esphome:
  name: left-garage-door
  friendly_name: Left Garage

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: *REDACTED*

ota:
  - platform: esphome
    password: *REDACTED*

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Left-Garage-Door"
    password: *REDACTED*

captive_portal:

# --- Sensors ---
binary_sensor:
  # Door Closed Sensor - Normally Open (Pin 13)
  - platform: gpio
    pin:
      number: 13
      mode:
        input: true
        pulldown: true
    id: door_closed_sensor
    name: "Garage Door Closed"
    device_class: garage_door
    on_press:
      then:
        # Door has reached the closed position
        - cover.template.publish:
            id: garage_door
            state: CLOSED
            current_operation: IDLE
    on_release:
      then:
        - lambda: |-
            // Door leaving the closed position while relay active → opening
            if (id(garage_door_relay).state) {
              id(garage_door).current_operation = COVER_OPERATION_OPENING;
            }

  # Door Open Sensor - Normally Open (Pin 14)
  - platform: gpio
    pin:
      number: 14
      mode:
        input: true
        pulldown: true
    id: door_open_sensor
    name: "Garage Door Open"
    device_class: garage_door
    on_press:
      then:
        # Door has reached the open position
        - cover.template.publish:
            id: garage_door
            state: OPEN
            current_operation: IDLE
    on_release:
      then:
        - lambda: |-
            // Door leaving the open position while relay active → closing
            if (id(garage_door_relay).state) {
              id(garage_door).current_operation = COVER_OPERATION_CLOSING;
            }

# --- Relay Control (Pin 33) ---
output:
  - platform: gpio
    pin: 33
    id: garage_door_relay
      - delay: 250ms
      - output.turn_off: garage_door_relay

# --- Template Cover ---
cover:
  - platform: template
    name: "Garage Door"
    device_class: garage
    id: garage_door
    lambda: |-
      // Determine door state from sensors
      if (id(door_open_sensor).state) {
        return COVER_OPEN;
      } else if (id(door_closed_sensor).state) {
        return COVER_CLOSED;
      } else {
        return COVER_OPEN;  // In motion or intermediate
      }
    open_action:
      - if:
          condition:
            not:
              binary_sensor.is_on: door_open_sensor
          then:
            - cover.template.publish:
                id: garage_door
                current_operation: OPENING
            - output.turn_on: garage_door_relay

    close_action:
      - if:
          condition:
            not:
              binary_sensor.is_on: door_closed_sensor
          then:
            - cover.template.publish:
                id: garage_door
                current_operation: CLOSING
            - output.turn_on: garage_door_relay

    stop_action:
      - output.turn_on: garage_door_relay
      - cover.template.publish:
          id: garage_door
          current_operation: IDLE
          
