#Working ESP Home Config for my First PCB Lets call it Version 1.1 (due to a few soldering missteps)
esphome:
  name: namehere #name used for mdns? ie namehere.local
  friendly_name: friendly name here

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "REDACTED"

ota:
  - platform: esphome
    password: "REDACTED"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot"
    password: "REDACTED"

#define contact sensors on input pins
binary_sensor:
  - platform: gpio
    pin: 35
    id: door_closed
    name: Door Closed
  - platform: gpio
    pin: 34
    id: door_open
    name: Door Open

#"Momentary" Switch to trigger Open/Close Relay
switch:
  - platform: gpio
    pin: 33
    device_class: switch
    id: open_close_relay
    name: Open Close Garage
    on_turn_on: 
      - delay: 250ms
      - switch.turn_off: open_close_relay
    internal: True

#define Garage Door Features, Functions, Logged events
cover:
  - platform: feedback
    name: Left Garage Door
    id: left_garage_door
    device_class: garage
    has_built_in_endstop: true
    max_duration: 
      seconds: 25
    open_action:
    - switch.turn_on: open_close_relay
    open_endstop: door_open
    open_duration: 
      seconds: 21
    close_action: 
    - switch.turn_on: open_close_relay
    close_endstop: door_closed
    close_duration: 
      seconds: 21
    stop_action: 
      then:
        - logger.log: Stop Action Performed!
    on_open: 
      then:
      - logger.log: Left Garage Door is Open!
    on_closed: 
      then:
        - logger.log: Left Garage Door is Closed!

web_server:
  port: 80
    
captive_portal:
    
