#Working ESP Home Config for my First PCB Lets call it Version 1.1 (due to a few soldering missteps)
#version 1.1.6 - 13/8/25
esphome:
  name: namehere #name used for mdns? ie namehere.local
  friendly_name: friendly name here

esp32:
  board: esp32dev #set to board being used.
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "REDACTED"

ota:
  - platform: esphome
    password: "REDACTED"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot"
    password: "REDACTED"

#define contact sensors on input pins
binary_sensor: # Previously had these two binary sensors as 34 & 35 mistake no pullup/pulldown resistors built in
  - platform: gpio
    id: door_closed
    pin:
      number: 13
      mode:
        input: true
        pulldown: true
    internal: True
    name: Door Closed
    
  - platform: gpio
    pin:
      number: 14
      mode:
        input: true
        pulldown: true
    id: door_open
    internal: True
    name: Door Open

  - platform: template
    name: Door state
    lambda: |-
      if (id(door_closed).state == true) {
        return false;
        } else {
          return true;
        }
    device_class: door

#"Momentary" Switch to trigger Open/Close Relay
switch:
  - platform: gpio
    pin: 48
    device_class: switch
    id: open_close_relay
    name: Open Close Garage
    on_turn_on: 
      - delay: 250ms
      - switch.turn_off: open_close_relay
    internal: True

#define Garage Door Features, Functions, Logged events
cover:
  - platform: feedback
    name: Right Garage Door
    id: right_garage_door
    device_class: garage
    has_built_in_endstop: true
    direction_change_wait_time: 
      seconds: 2
    open_action:
    - switch.turn_on: open_close_relay
    open_endstop: door_open
    open_duration: 
      seconds: 17
    close_action: 
    - switch.turn_on: open_close_relay
    close_endstop: door_closed
    close_duration: 
      seconds: 17
    stop_action: 
    - switch.turn_on: open_close_relay
    on_open: 
      then:
      - logger.log: Right Garage Door is Open!
    on_closed: 
      then:
        - logger.log: Right Garage Door is Closed!
        
captive_portal:
    
